# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170518_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='newField',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Student'),
        ),
    ]
