# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 06:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='imagefield',
            field=models.ImageField(blank=True, null=True, upload_to='myapp/images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numpages',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
